lines: 2
cols: 6
images:
  - image: sample/test.jpg
    text: test 1
  - image: sample/test.jpg
    text: test 2
  - image: sample/test.jpg
    text: test 3
  - image: sample/test.jpg
    text: test 4
  - image: sample/test.jpg
    text: test 5
  - image: sample/test.jpg
    text: test 6
  - image: sample/test.jpg
    text: test 7
  - image: sample/test.jpg
    text: test 8
