page:
  twoSidedOffsetMM:
    x: -3
    y: 0
  cols: 3
  lines: 3
  orientation: landscape
  page_margins:
    top: 45
    bottom: 45
    left: 45
    right: 45
#  margins:
#    top: 10
#    bottom: 10
#    left: 30
#    right: 30
#  paddings:
#    top: 2
#    bottom: 2
#    left: 2
#    right: 2
text:
  # font: /some/font.ttf
  ratio: 1/6
  color: steelblue
  top: true # Put the text at the top of the cell
  definitions:
    # font: /some/font
    size: 28
    color: tomato
images:
  - image: sample/jap.jpg
    text: Geisha 1
    textColors:
      0: tomato
    def:
      text: I am a Geisha 1
      font: config/OleoScript-Regular.ttf
      size: 12
      color: green
      textColors:
        0: tomato
        14: tomato
  - image: sample/jap.jpg
    text: Geisha 2
    textColors:
      1: tomato
    def:
      text: I am a Geisha 2
  - image: sample/jap.jpg
    text: Geisha 3
    textColors:
      2: tomato
    def:
      text: I am a Geisha 3
      font: config/Combo-Regular.ttf
      size: 19
      color: blue
      textColors:
        5: yellow
        8: green
  - image: sample/jap.jpg
    text: Geisha 4
    textColors:
      3: tomato
    def:
      text: I am a Geisha 4
  - image: sample/jap.jpg
    text: Geisha 5
    textColors:
      4: tomato
    def:
      text: I am a Geisha 5
      font: /home/nmaupu/downloads/Combo-Regular.ttf
  - image: sample/jap.jpg
    text: Geisha 6
    textColors:
      5: tomato
    def:
      text: I am a Geisha 6
