cols: 2
images:
  - image: sample/crayons.jpg
    text: Crayons
  - image: sample/corrosif.jpg
    text: Corrosif
  - image: sample/test2.jpg
    text: test 2
  - image: sample/interdit.png
    text: Interdit !
  - image: sample/corrosif.jpg
    text: test 4
  - image: sample/corrosif.jpg
    text: test 5
  - image: sample/corrosif.jpg
    text: test 6
  - image: sample/corrosif.jpg
    text: test 7
  - image: sample/corrosif.jpg
    text: test 8
