page:
  cols: 3
  lines: 3
  orientation: landscape
# page_margins:
#   top: 15
#   bottom: 15
#   left: 15
#   right: 15
# margins:
#   top: 5.67 / 2
#   bottom: 5.67 / 2
#   left: 5.67 / 2
#   right: 5.67 / 2
# paddings:
#   top: 2
#   bottom: 2
#   left: 2
#   right: 2
text:
  #font: /some/font.ttf
  ratio: 1/6
  color: steelblue
  firstLetterColor: tomato
images:
  - image: sample/jap.jpg
    text: Geisha
  - image: sample/crayons.jpg
    text: Crayons
  - image: sample/panorama.jpg
    text: Paysage
  - image: sample/carcrash.jpg
    text: Accident
  - image: sample/corrosif.jpg
    text: Corrosif
  - image: sample/test2.jpg
    text: test 2
  - image: sample/interdit.png
    text: Interdit !
  - image: sample/corrosif.jpg
    text: test 4
  - image: sample/corrosif.jpg
    text: test 5
  - image: sample/corrosif.jpg
    text: test 6
  - image: sample/corrosif.jpg
    text: test 7
  - image: sample/corrosif.jpg
    text: test 8
  - image: sample/corrosif.jpg
    text: Corrosif
  - image: sample/test2.jpg
    text: test 2
  - image: sample/interdit.png
    text: Interdit !
  - image: sample/corrosif.jpg
    text: test 4
  - image: sample/corrosif.jpg
    text: test 5
  - image: sample/corrosif.jpg
    text: test 6
