page:
  twoSidedOffsetMM:
    x: -3
    y: 0
  cols: 3
  lines: 3
  orientation: landscape
  page_margins:
    top: 45
    bottom: 45
    left: 45
    right: 45
#  margins:
#    top: 10
#    bottom: 10
#    left: 30
#    right: 30
#  paddings:
#    top: 2
#    bottom: 2
#    left: 2
#    right: 2
text:
  # font: /some/font.ttf
  ratio: 1/6
  color: steelblue
  top: true # Put the text at the top of the cell
  definitions:
    # font: /some/font
    size: 28
    color: tomato
    borders: true
images:
  - image: sample/jap.jpg
    text: Geisha 1
    textColors:
      0: tomato
    def:
      text: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
      font: config/OleoScript-Regular.ttf
      size: 10
      lineSpacingRatio: .3
      color: green
      textColors:
        0: tomato
        15: tomato
        146: tomato
        147: tomato
        148: tomato
        149: tomato
        243: tomato
  - image: sample/jap.jpg
    text: Geisha 2
  - image: sample/jap.jpg
    text: Geisha 3
  - image: sample/jap.jpg
    text: Geisha 4
  - image: sample/jap.jpg
    text: Geisha 5
  - image: sample/jap.jpg
    text: Geisha 6
